<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="motion_detection.zip" />
    <None Remove="PythonFiles.zip" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="motion_detection.zip" />
    <EmbeddedResource Include="Python.zip" />
    <EmbeddedResource Include="PythonFiles.zip" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="inpsNuGet" Version="1.1.20" />
  </ItemGroup>

</Project>